# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: a.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='a.proto',
  package='a',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x07\x61.proto\x12\x01\x61\"&\n\nFooMessage\x12\x0b\n\x03\x61\x61\x61\x18\x01 \x01(\x03\x12\x0b\n\x03\x62\x62\x62\x18\x02 \x01(\t\"(\n\nFooRequest\x12\x1a\n\x03\x66oo\x18\x01 \x01(\x0b\x32\r.a.FooMessage\"\x1e\n\x0b\x46ooResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x34\n\nFooService\x12&\n\x03\x66oo\x12\r.a.FooRequest\x1a\x0e.a.FooResponse\"\x00\x62\x06proto3'
)




_FOOMESSAGE = _descriptor.Descriptor(
  name='FooMessage',
  full_name='a.FooMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='aaa', full_name='a.FooMessage.aaa', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bbb', full_name='a.FooMessage.bbb', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=52,
)


_FOOREQUEST = _descriptor.Descriptor(
  name='FooRequest',
  full_name='a.FooRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='foo', full_name='a.FooRequest.foo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=94,
)


_FOORESPONSE = _descriptor.Descriptor(
  name='FooResponse',
  full_name='a.FooResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='a.FooResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=126,
)

_FOOREQUEST.fields_by_name['foo'].message_type = _FOOMESSAGE
DESCRIPTOR.message_types_by_name['FooMessage'] = _FOOMESSAGE
DESCRIPTOR.message_types_by_name['FooRequest'] = _FOOREQUEST
DESCRIPTOR.message_types_by_name['FooResponse'] = _FOORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FooMessage = _reflection.GeneratedProtocolMessageType('FooMessage', (_message.Message,), {
  'DESCRIPTOR' : _FOOMESSAGE,
  '__module__' : 'a_pb2'
  # @@protoc_insertion_point(class_scope:a.FooMessage)
  })
_sym_db.RegisterMessage(FooMessage)

FooRequest = _reflection.GeneratedProtocolMessageType('FooRequest', (_message.Message,), {
  'DESCRIPTOR' : _FOOREQUEST,
  '__module__' : 'a_pb2'
  # @@protoc_insertion_point(class_scope:a.FooRequest)
  })
_sym_db.RegisterMessage(FooRequest)

FooResponse = _reflection.GeneratedProtocolMessageType('FooResponse', (_message.Message,), {
  'DESCRIPTOR' : _FOORESPONSE,
  '__module__' : 'a_pb2'
  # @@protoc_insertion_point(class_scope:a.FooResponse)
  })
_sym_db.RegisterMessage(FooResponse)



_FOOSERVICE = _descriptor.ServiceDescriptor(
  name='FooService',
  full_name='a.FooService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=128,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='foo',
    full_name='a.FooService.foo',
    index=0,
    containing_service=None,
    input_type=_FOOREQUEST,
    output_type=_FOORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FOOSERVICE)

DESCRIPTOR.services_by_name['FooService'] = _FOOSERVICE

# @@protoc_insertion_point(module_scope)
