# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import a_pb2 as a__pb2


class FooServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.foo = channel.unary_unary(
                '/a.FooService/foo',
                request_serializer=a__pb2.FooRequest.SerializeToString,
                response_deserializer=a__pb2.FooResponse.FromString,
                )


class FooServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def foo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FooServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'foo': grpc.unary_unary_rpc_method_handler(
                    servicer.foo,
                    request_deserializer=a__pb2.FooRequest.FromString,
                    response_serializer=a__pb2.FooResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a.FooService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FooService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def foo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/a.FooService/foo',
            a__pb2.FooRequest.SerializeToString,
            a__pb2.FooResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
